import {
    findSubmissionsByPaperId,
    findSubmissionsByUserId,
    createSubmission,
} from "@/lib/repositories/submission.repository";

import {
    findResearchPaperById,
} from "@/lib/repositories/research-paper.repository";

import {
    findResearchGroupById,
} from "@/lib/repositories/research-group.repository";

import {
    findGroupMember,
} from "@/lib/repositories/group-member.repository";

import type { ServiceResult } from "@/types/auth";

/**
 * Represents a submission returned by
 * the submission service.
 */
export interface ManagedSubmission {
    id: number;
    paperId: number;
    submittedBy: number;
    version: string;
    fileUrl: string;
    remarks: string | null;
    status: string;
    submittedAt: Date;
}

/**
 * Retrieves all submissions belonging
 * to a research paper.
 */
export async function getSubmissionsByPaper(
    paperId: number
): Promise<ServiceResult<ManagedSubmission[]>> {
    const paper =
        await findResearchPaperById(
            paperId
        );

    if (!paper) {
        return {
            success: false,
            message: "Research paper not found.",
        };
    }

    const submissions =
        await findSubmissionsByPaperId(
            paperId
        );

    return {
        success: true,
        message:
            "Submissions retrieved successfully.",
        data: submissions,
    };
}

/**
 * Retrieves all submissions made by
 * a specific Student.
 */
export async function getSubmissionsByStudent(
    studentId: number
): Promise<ServiceResult<ManagedSubmission[]>> {
    const submissions =
        await findSubmissionsByUserId(
            studentId
        );

    return {
        success: true,
        message:
            "Student submissions retrieved successfully.",
        data: submissions,
    };
}

/**
 * Determines the next submission version
 * for a research paper.
 *
 * Version numbers are generated by the
 * server instead of being supplied by
 * the client.
 */
async function getNextSubmissionVersion(
    paperId: number
): Promise<string> {
    const submissions =
        await findSubmissionsByPaperId(
            paperId
        );

    return `v${submissions.length + 1}`;
}

/**
 * Creates a new submission for a Student.
 *
 * The service verifies that:
 *
 * 1. The research paper exists.
 * 2. The research group exists.
 * 3. The Student belongs to the group.
 * 4. The submitted file information exists.
 *
 * The submission version is generated
 * automatically by the server.
 */
export async function submitResearch(
    paperId: number,
    studentId: number,
    fileUrl: string,
    remarks?: string
): Promise<ServiceResult<ManagedSubmission>> {
    const paper =
        await findResearchPaperById(
            paperId
        );

    if (!paper) {
        return {
            success: false,
            message: "Research paper not found.",
        };
    }

    const group =
        await findResearchGroupById(
            paper.groupId
        );

    if (!group) {
        return {
            success: false,
            message:
                "Research group associated with this paper was not found.",
        };
    }

    const membership =
        await findGroupMember(
            paper.groupId,
            studentId
        );

    if (!membership) {
        return {
            success: false,
            message:
                "Student is not a member of this research group.",
        };
    }

    if (!fileUrl.trim()) {
        return {
            success: false,
            message:
                "A submission file is required.",
        };
    }

    const version =
        await getNextSubmissionVersion(
            paperId
        );

    const submission =
        await createSubmission({
            paperId,
            submittedBy: studentId,
            version,
            fileUrl,
            remarks:
                remarks?.trim() || null,
            status: "Submitted",
        });

    return {
        success: true,
        message:
            "Research submitted successfully.",
        data: submission,
    };
}